# Generated by Django 4.1.6 on 2023-12-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_coverphoto_deceased_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceased',
            name='relationship_type',
            field=models.CharField(blank=True, choices=[('mother', 'mother'), ('father', 'father'), ('brother', 'brother'), ('sister', 'sister'), ('nephew', 'nephew'), ('cousin', 'cousin'), ('neice', 'neice'), ('grand mother', 'grand mother'), ('grand father', 'grand father')], max_length=20, null=True),
        ),
    ]
