# Generated by Django 4.1.6 on 2023-12-11 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_deceased_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='deceased',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_cover', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deceased',
            name='share',
            field=models.ManyToManyField(blank=True, null=True, related_name='share', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TributeReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('heart', models.ManyToManyField(blank=True, related_name='tribute_heart_reply', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='tribute_liked_reply', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.tributereply')),
                ('tribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tribute_replies', to='App.tribute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tribute',
            name='deceased',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.deceased'),
        ),
        migrations.AddField(
            model_name='tribute',
            name='heart',
            field=models.ManyToManyField(blank=True, related_name='heart_tribute', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tribute',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_tribute', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tribute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
